ARG FRAPPE_BRANCH=develop
ARG FRAPPE_PINNED_COMMIT=80d6f8767113e2d16f8a451367e387d9c8469c43
ARG ERPNEXT_PINNED_COMMIT=0e8b152c680fd9db0663f60057ecb5af59c30bef
ARG HRMS_PINNED_COMMIT=bd9eb262b871c454349a59e662b0cde698da2d25
ARG CRM_PINNED_COMMIT=4b3d6fcd102b4db5b2295b2170089644558c0323
ARG FRAPPE_IMAGE_PREFIX=frappe
ARG FRAPPE_BUILD_IMAGE=frappe/build:develop@sha256:838827aebecbceb1382ec414bc8351cef838c10e9d672caa4eb329d141278ac6
ARG FRAPPE_BASE_IMAGE=frappe/base:develop@sha256:08bb76672ee086d30c49ffd12db12a28faa132de72257cb662f65be612b79128

FROM ${FRAPPE_BUILD_IMAGE} AS builder

ARG FRAPPE_BRANCH=develop
ARG FRAPPE_PINNED_COMMIT=80d6f8767113e2d16f8a451367e387d9c8469c43
ARG ERPNEXT_PINNED_COMMIT=0e8b152c680fd9db0663f60057ecb5af59c30bef
ARG HRMS_PINNED_COMMIT=bd9eb262b871c454349a59e662b0cde698da2d25
ARG CRM_PINNED_COMMIT=4b3d6fcd102b4db5b2295b2170089644558c0323
ARG FRAPPE_PATH=https://github.com/frappe/frappe
ARG CACHE_BUST=""

USER frappe

RUN --mount=type=secret,id=apps_json,target=/opt/frappe/apps.json,uid=1000,gid=1000 \
  : "${CACHE_BUST}" && \
  export APP_INSTALL_ARGS="" && \
  if [ -f /opt/frappe/apps.json ] && [ -s /opt/frappe/apps.json ]; then \
    export APP_INSTALL_ARGS="--apps_path=/opt/frappe/apps.json"; \
  fi && \
  bench init ${APP_INSTALL_ARGS}\
    --frappe-branch=${FRAPPE_BRANCH} \
    --frappe-path=${FRAPPE_PATH} \
    --no-procfile \
    --no-backups \
    --skip-redis-config-generation \
    --verbose \
    /home/frappe/frappe-bench && \
  cd /home/frappe/frappe-bench && \
  git -C apps/frappe fetch --depth 1 origin ${FRAPPE_PINNED_COMMIT} && \
  git -C apps/frappe checkout --force --detach ${FRAPPE_PINNED_COMMIT} && \
  git -C apps/erpnext fetch --depth 1 origin ${ERPNEXT_PINNED_COMMIT} && \
  git -C apps/erpnext checkout --force --detach ${ERPNEXT_PINNED_COMMIT} && \
  git -C apps/hrms fetch --depth 1 origin ${HRMS_PINNED_COMMIT} && \
  git -C apps/hrms checkout --force --detach ${HRMS_PINNED_COMMIT} && \
  git -C apps/crm fetch --depth 1 origin ${CRM_PINNED_COMMIT} && \
  git -C apps/crm checkout --force --detach ${CRM_PINNED_COMMIT} && \
  echo "{}" > sites/common_site_config.json && \
  find apps -mindepth 1 -path "*/.git" | xargs rm -fr

FROM ${FRAPPE_BASE_IMAGE} AS backend

USER frappe

COPY --from=builder --chown=frappe:frappe /home/frappe/frappe-bench /home/frappe/frappe-bench

WORKDIR /home/frappe/frappe-bench

# Move assets to image-layer storage
RUN cp -r /home/frappe/frappe-bench/sites/assets /home/frappe/frappe-bench/assets && \
  rm -rf /home/frappe/frappe-bench/sites/assets

# Cartertek deployment-level Frappe CRM desktop launcher icon assets.
# These are baked into the image so /assets/frappe_crm_desktop_icons/* is
# available to both backend and frontend containers after entrypoint asset linking.
COPY --chown=frappe:frappe resources/cartertek/frappe-crm-desktop-icons /home/frappe/frappe-bench/assets/frappe_crm_desktop_icons

VOLUME [ \
  "/home/frappe/frappe-bench/sites", \
  "/home/frappe/frappe-bench/logs" \
]

USER root
# This entrypoint script link build assets of the image to the mounted sites volume at container initialization
COPY resources/core/main-entrypoint.sh /usr/local/bin/entrypoint.sh
RUN chmod 755 /usr/local/bin/entrypoint.sh

COPY resources/core/start.sh /usr/local/bin/start.sh
RUN chmod 755 /usr/local/bin/start.sh

COPY resources/core/finalize-deployment.sh /usr/local/bin/finalize-deployment.sh
RUN chmod 755 /usr/local/bin/finalize-deployment.sh

USER frappe
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

CMD ["start.sh"]
